spring:
  application:
    name: spring_jpa_relations
  datasource:
    url: jdbc:postgresql://localhost:5433/test_db
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
server:
  port: 9090