spring:
  application:
    name: ms-inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8082
